<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\egis.controls\EGIS.Controls.csproj" />
    <ProjectReference Include="..\EGIS.Projections\EGIS.Projections.csproj" />
    <ProjectReference Include="..\egis.ShapeFileLib\EGIS.ShapeFileLib.csproj" />
  </ItemGroup>

</Project>