<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile>egis.snk</AssemblyOriginatorKeyFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Version>4.8.9</Version>
    <Authors>Winston Fletcher</Authors>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Description>Easy GIS .NET Desktop Map Controls</Description>
    <PackageTags>C# GIS Map Control; Easy GIS .NET; C# GIS library</PackageTags>
    <RepositoryUrl>https://github.com/wfletcher/EasyGIS.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://www.easygisdotnet.com/</PackageProjectUrl>
    <Copyright>Copyright © 2008-2025 Winston Fletcher</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <Nullable>disable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="CsvToShapeFileControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="CRSSelectionControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="SFMap.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="ShapeFileListControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Service Include="{94E38DFF-614B-4cbd-B67C-F211BB35CE8B}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EGIS.Projections\EGIS.Projections.csproj" />
    <ProjectReference Include="..\egis.ShapeFileLib\EGIS.ShapeFileLib.csproj" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="System.Net.Http" />
  </ItemGroup> 
</Project>