<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile>egis.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Version>4.8.8</Version>
    <Authors>Winston Fletcher</Authors>
    <Description>Official version of EasyGIS.NET ShapeFileLib. Includes C# ShapeFile Reader Writer</Description>
    <RepositoryUrl>https://github.com/wfletcher/EasyGIS.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://www.easygisdotnet.com</PackageProjectUrl>
    <Copyright>Copyright © 2008-2023 Winston Fletcher</Copyright>
    <PackageTags>C# shapefile library; Easy GIS .NET; C# GIS library shapefile reader writer</PackageTags>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <Nullable>disable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Include="egis.pfx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="geomutil_lib.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Include="geomutil_libx64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EGIS.Projections\EGIS.Projections.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="build\net47\**" Pack="true" PackagePath="\build\net47" />
  </ItemGroup>
</Project>