<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>egis.snk</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Proj\proj.db">
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackagePath>contentFiles\any\any\Proj</PackagePath>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Proj\x64\proj_9_0.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackagePath>contentFiles\any\any\Proj\x64</PackagePath>
    </Content>
    <Content Include="Proj\x64\sqlite3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackagePath>contentFiles\any\any\Proj\x64</PackagePath>
    </Content>
    <Content Include="Proj\x86\proj_9_0.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackagePath>contentFiles\any\any\Proj\x86</PackagePath>
    </Content>
    <Content Include="Proj\x86\sqlite3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackagePath>contentFiles\any\any\Proj\x86</PackagePath>
    </Content>
    <None Update="Proj\proj_license.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <PackageId>$(AssemblyTitle)</PackageId>
    <Version>4.8.9</Version>
    <Authors>Winston Fletcher</Authors>
    <Company>$(Company)</Company>
    <Description>Easy GIS .NET GIS Projections Class Library.
C# wrapper of native proj_9_0 library</Description>
    <PackageProjectUrl>https://www.easygisdotnet.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/wfletcher/EasyGIS.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <Copyright>Copyright © 2008-2025 Winston Fletcher</Copyright>
    <PackageTags>Easy GIS .NET Projection Library, native proj 9.0 C# wrapper</PackageTags>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Nullable>disable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
</Project>